server:
  port: 8088
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/quiz-app
    password: root123
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true


  mail:
    host: smtp.gmail.com
    password: zdtwivdlvbcqyrws
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: azizabdualiyev6@gmail.com
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days



